[build]
  command = "pnpm --filter @hammercreative/web build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "10.12.4"

[dev]
  command = "pnpm --filter @hammer/web dev"
  framework = "#custom"
  targetPort = 3000
  port = 8888

[[plugins]]
  package = "@netlify/plugin-nextjs"
